[package]
name = "viewer"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true


[dependencies]
bevy.workspace = true
bevy_egui.workspace = true

chaotic.workspace = true
